apiVersion: v1
kind: Pod
metadata:
  name: copier
  namespace: cgit
spec:
  volumes:
    - name: cgit-repositories
      persistentVolumeClaim:
        claimName: cgit-repositories
  containers:
    - name: copier
      image: alpine
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "apk add git; while true; do sleep 30; done;" ]
      volumeMounts:
        - mountPath: /var/www/htdocs/cgit/repositories/
          name: cgit-repositories