apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cgit
  name: cgit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgit
  template:
    metadata:
      labels:
        app: cgit
    spec:
      containers:
      - name: cgit
        image: truebad0ur/cgit:0.4-aarch64
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/www/htdocs/cgit/repositories/
          name: cgit-repositories
      volumes:
      - name: cgit-repositories
        persistentVolumeClaim:
          claimName: cgit-repositories
---
apiVersion: v1
kind: Service
metadata:
  namespace: cgit
  name: cgit
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: cgit
