apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cgit-repositories
  namespace: cgit
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
